if(HAVE_COMPACT)
  add_subdirectory(compact)
endif()
if(HAVE_COMPRESS)
  add_subdirectory(compress)
endif()
if(HAVE_CONST)
  add_subdirectory(const)
endif()
if(HAVE_FAR)
  add_subdirectory(far)
endif()
if(HAVE_LINEAR)
  add_subdirectory(linear)
endif()
if(HAVE_LOOKAHEAD)
  add_subdirectory(lookahead)
endif()
if(HAVE_MPDT)
  add_subdirectory(mpdt)
endif()
if(HAVE_NGRAM)
  add_subdirectory(ngram)
endif()
if(HAVE_PDT)
  add_subdirectory(pdt)
endif()
if(HAVE_PYTHON)
  add_subdirectory(python)
endif()
if(HAVE_SPECIAL)
  add_subdirectory(special)
endif()
